export const metadata = {
  title: "Chat app",
  description: "Generated by Next.js",
};
import "../style/global.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="header">
          <h1 className="header-title">Chat app</h1>
        </header>
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
